# Generated by Django 4.2.5 on 2023-09-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptin',
            new_name='description',
        ),
    ]
